version: "3.9"
# docker pull clickhouse/clickhouse-server:24.3.12.75-alpine
services:
  share-note-server:
    build: .
    restart: on-failure:5
    ports:
    - 5000:5000
    volumes:
    - './config.yaml:/config.yaml'
    - './data:/data'